name:                HaskTerm
version:             0.1.0.0
github:              "JesterOrNot/HaskTerm"
license:             MIT
author:              "Sean Hellum"
maintainer:          "seanhellum45@gmail.com"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: unix shell written in Haskell

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskterm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskTerm

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskTerm
