name: HaskShell
version: 0.1.0.0
github: "JesterOrNot/HaskShell"
license: MIT
author: "Sean Hellum"
maintainer: "seanhellum45@gmail.com"
extra-source-files:
  - README.md
description: unix shell written in Haskell
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  dependencies:
    - process
    - transformers
executables:
  haskshell:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HaskShell
      - haskeline
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HaskShell
